command_timeout = 1500

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
[░▒▓](#94e2d5)\
[ ](bg:#94e2d5 fg:#090c0c)\
$os\
$username\
[](fg:#94e2d5 bg:#394260)\
$directory\
[](fg:#394260 bg:#8c97c0)\
$git_branch\
$git_status\
[](fg:#8c97c0 bg:#1d2230)\
$nodejs\
$rust\
$golang\
$php\
$time\
[](fg:#1d2230)\
\n$character"""

[hostname]
ssh_only = true
format = '[$hostname](bold red) '
disabled = false

[os]
disabled = false
style = "fg:#394260 bg:#94e2d5"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:#394260 bg:#94e2d5"
format = '[ $user ]($style)'

[directory]
style = "fg:#94e2d5 bg:#394260"
format = "[ $path ]($style)"
truncation_length = 12
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "fg:#1d2230 bg:#8c97c0"
format = '[[ $symbol $branch ](fg:#1d2230 bg:#8c97c0)]($style)'

[git_status]
style = "fg:#1d2230 bg:#8c97c0"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#215732 bg:#1d2230)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#94e2d5 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#94e2d5 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#94e2d5 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#8c97c0 bg:#1d2230)]($style)'

[character]
success_symbol = "[❯](fg:#94e2d5)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[❮](fg:red)"
